import { useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { AlertTriangle, Columns3 } from 'lucide-react'
import { api, type ResearchExperiment } from '@/lib/api'
import { QK } from '@/lib/queryKeys'

function stringify(value: unknown) {
  return value == null ? '—' : typeof value === 'string' ? value : JSON.stringify(value)
}

function ExperimentColumn({ experiment }: { experiment: ResearchExperiment }) {
  const subject = experiment.subject.kind === 'factor' ? `因子修订版 ${experiment.subject.revision_id}` : `注册策略 ${experiment.subject.id} · ${experiment.subject.version}`
  return <article className="min-w-0 rounded-btn border border-border bg-base/25 p-3 text-xs"><h3 className="font-semibold text-foreground">{subject}</h3><p className="mt-1 text-muted">快照 {experiment.id} · 保留于 {experiment.retained_at}</p><dl className="mt-3 space-y-2"><div><dt className="text-muted">已解析配置</dt><dd className="mt-0.5 break-words font-mono text-[11px]">{stringify(experiment.resolved_config)}</dd></div><div><dt className="text-muted">受治理输入清单</dt><dd className="mt-0.5 break-words font-mono text-[11px]">{stringify(experiment.input_manifest)}</dd></div><div><dt className="text-muted">预测 / 信号</dt><dd className="mt-0.5 break-words font-mono text-[11px]">{stringify(experiment.prediction_signals)}</dd></div><div><dt className="text-muted">度量（Pearson IC 与 RankIC 独立）</dt><dd className="mt-0.5 break-words font-mono text-[11px]">{stringify(experiment.metrics)}</dd></div><div><dt className="text-muted">工件</dt><dd className="mt-0.5 break-words font-mono text-[11px]">{JSON.stringify(experiment.artifacts)}</dd></div><div><dt className="text-muted">模型 / 提供商版本</dt><dd className="mt-0.5 break-words font-mono text-[11px]">{JSON.stringify(experiment.model_provenance)}</dd></div></dl></article>
}

export function ExperimentComparison() {
  const [selected, setSelected] = useState<string[]>([])
  const candidates = useQuery({ queryKey: QK.researchComparisonCandidates, queryFn: api.researchComparisonCandidates })
  const comparison = useMutation({ mutationFn: (ids: string[]) => api.compareResearchExperiments(ids) })
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id])

  return <section aria-label="实验比较" className="rounded-card border border-border bg-surface p-3"><div className="flex items-center gap-2"><Columns3 className="h-4 w-4 text-accent" /><div><h2 className="text-sm font-semibold">显式并排比较</h2><p className="text-xs text-muted">只有 API 提供的已完成且已保留候选可选。此处不计算优胜者或总分。</p></div></div><div className="mt-3 grid gap-2 md:grid-cols-2">{candidates.data?.experiments.length === 0 && <p className="text-xs text-muted">尚无可比较的已保留实验。</p>}{candidates.data?.experiments.map(experiment => <label key={experiment.id} className="flex cursor-pointer items-start gap-2 rounded-btn border border-border bg-base/25 p-2 text-xs"><input aria-label={`选择实验 ${experiment.id}`} type="checkbox" checked={selected.includes(experiment.id)} onChange={() => toggle(experiment.id)} /><span><strong>{experiment.subject.kind === 'factor' ? `因子 ${experiment.subject.revision_id}` : `策略 ${experiment.subject.id} ${experiment.subject.version}`}</strong><br /><span className="text-muted">{experiment.created_at} · 已保留</span></span></label>)}</div><button type="button" disabled={selected.length < 2 || comparison.isPending} onClick={() => comparison.mutate(selected)} className="mt-3 rounded-btn bg-accent px-3 py-1.5 text-xs font-medium text-white disabled:opacity-40">比较已选实验（{selected.length}）</button>{comparison.isError && <p role="alert" className="mt-2 text-xs text-danger">无法比较：{comparison.error.message}</p>}{comparison.data && <div className="mt-3 space-y-3">{comparison.data.warnings.length > 0 ? <aside aria-label="兼容性警告" className="rounded-btn border border-amber-400/40 bg-amber-400/10 p-3 text-xs text-amber-600"><div className="flex items-center gap-1 font-semibold"><AlertTriangle className="h-3.5 w-3.5" />兼容性警告</div><ul className="mt-1 list-disc pl-4">{comparison.data.warnings.map(warning => <li key={warning}>{warning}</li>)}</ul></aside> : <aside aria-label="兼容性警告" className="rounded-btn border border-bull/30 bg-bull/10 p-3 text-xs text-bull">未发现 universe、时间窗口、horizon 或数据修订不匹配。</aside>}<div className="grid gap-3 xl:grid-cols-2">{comparison.data.experiments.map(experiment => <ExperimentColumn key={experiment.id} experiment={experiment} />)}</div><details className="rounded-btn border border-border p-2 text-xs"><summary className="cursor-pointer font-medium text-secondary">显式字段差异（不隐藏不匹配）</summary><pre className="mt-2 overflow-x-auto whitespace-pre-wrap break-words text-[11px] text-muted">{JSON.stringify(comparison.data.deltas, null, 2)}</pre></details></div>}</section>
}
